const knygos = [
  {
    Fiction: [
      {
        ISBN: "F-12345",
        Released: 1913,
        Name: '"In Search of Lost Time"',
        Pages: 207,
        Amount: 6,
        Price: "60 EUR",
      },
      {
        ISBN: "F-54321",
        Released: 1904,
        Name: '"Ulysses"',
        Pages: 306,
        Amount: 9,
        Price: "80 EUR",
      },
      {
        ISBN: "F-98765",
        Released: 1987,
        Name: '"Don Quixote"',
        Pages: 406,
        Amount: 4,
        Price: "110 EUR",
      },
      {
        ISBN: "F-67890",
        Released: 2005,
        Name: '"One Hundred Years of Solitude"',
        Pages: 301,
        Amount: 13,
        Price: "65 EUR",
      },
      {
        ISBN: "F-56743",
        Released: 1956,
        Name: '"The Great Gatsby"',
        Pages: 305,
        Amount: 15,
        Price: "90 EUR",
      },
    ],
  },
  {
    Biography: [
      {
        ISBN: "B-12345",
        Released: 1998,
        Name: '"A Beautiful Mind"',
        Pages: 208,
        Amount: 10,
        Price: "40 EUR",
      },
      {
        ISBN: "B-54321",
        Released: 2005,
        Name: '"Churchill: A Life"',
        Pages: 408,
        Amount: 5,
        Price: "55 EUR",
      },
      {
        ISBN: "B-98765",
        Released: 1987,
        Name: '"Alexander Hamilton"',
        Pages: 389,
        Amount: 17,
        Price: "50 EUR",
      },
      {
        ISBN: "B-56789",
        Released: 2008,
        Name: '"Enriques Journey"',
        Pages: 405,
        Amount: 16,
        Price: "378 EUR",
      },
      {
        ISBN: "B-67483",
        Released: 1992,
        Name: '"Into the Wild"',
        Pages: 506,
        Amount: 20,
        Price: "70 EUR",
      },
    ],
  },
  {
    Mystery: [
      {
        ISBN: "M-12345",
        Released: 2001,
        Name: '"And Then There Were None"',
        Pages: 309,
        Amount: 22,
        Price: "40 EUR",
      },
      {
        ISBN: "M-54321",
        Released: 2006,
        Name: '"The Big Sleep"',
        Pages: 284,
        Amount: 14,
        Price: "30 EUR",
      },
      {
        ISBN: "M-98765",
        Released: 2008,
        Name: '"Gone Girl"',
        Pages: 377,
        Amount: 18,
        Price: "60 EUR",
      },
      {
        ISBN: "M-67890",
        Released: 2004,
        Name: '"In Cold Blood"',
        Pages: 201,
        Amount: 10,
        Price: "45 EUR",
      },
      {
        ISBN: "M-78543",
        Released: 2006,
        Name: '"Woman in White"',
        Pages: 250,
        Amount: 19,
        Price: "55 EUR",
      },
    ],
  },
];
export default knygos;
